### ISSUE TITLE
constructor FileProvider in class FileProvider cannot be applied to given types

### ISSUE THREAD

**Issue by indapublic** [react-native-webview/react-native-webview#2978]
**Repository** [here](https://github.com/indapublic/reactnativewebviewissue)

**Versions**

```
react-native: 0.71.8

react-native-webview: 12.2.0
```

**Steps are:**

```
npx react-native@latest init reactnativewebviewissue

npm run android // All is fine

npm install --save react-native-webview

npm run android // Fault
```

**Error message:**

```
> Task :react-native-webview:compileDebugJavaWithJavac FAILED
37 actionable tasks: 24 executed, 13 up-to-date
/Volumes/Data/Workspace/github/reactnativewebviewissue/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewFileProvider.java:13: error: constructor FileProvider in class FileProvider cannot be applied to given types;
    super(R.xml.file_provider_paths);
    ^
  required: no arguments
  found: int
  reason: actual and formal argument lists differ in length
```

**Comment by jihokim2** [comment]
Please, Fix this.

**Comment by UNIDY2002** [comment]
@mganandraj

**Comment by rorisme** [comment]
I have the same issue. Any clue why this is happening?

**Comment by FelipeLimaDeSouza** [comment]
I have the same issue

**Comment by efstathiosntonas** [comment]
> I have the same issue. Downgrading to `11.26.1` seems to fix it.

no need to go all the way down to `11.x`, `"react-native-webview": "12.1.0"` works fine (notice no `^`, `~` before version)

On `12.1.0` the `RNCWebViewFileProvider` is intentionally left blank, on `12.2.0` is not.

**Comment by jiangyuanyuan** [comment]
I have the same issue

**Comment by willTerner** [comment]
> > I have the same issue. Downgrading to `11.26.1` seems to fix it.
> 
> no need to go all the way down to `11.x`, `"react-native-webview": "12.1.0"` works fine (notice no `^`, `~` before version)
> 
> On `12.1.0` the `RNCWebViewFileProvider` is intentionally left blank, on `12.2.0` is not.

But I can't install 12.2.1. The newest version is 12.2.0.

**Comment by hasitp-hkis** [comment]
I have the same issue.

**Comment by efstathiosntonas** [comment]
@willTerner it's `12.1.0` not `12.2.1`

**Comment by krishna-gujjjar** [comment]
I have the same issue with 

```json
"react": "18.2.0",
"react-native": "0.71.8",
"react-native-webview": "^12.2.0"
```

Error Message

```log
Task :react-native-webview:compileDebugJavaWithJavac FAILED
node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewFileProvider.java:13: error: constructor FileProvider in class FileProvider cannot be applied to given types;
  super(R.xml.file_provider_paths);
  ^
required: no arguments
found: int
reason: actual and formal argument lists differ in length
```

**Comment by aspidvip** [comment]
I have the same issue with

**Comment by RohanWeli** [comment]
I have the same issue

**Comment by neeteshraj** [comment]
I have the same issue in my react-native application.

**Comment by neeteshraj** [comment]
> I have the same issue in my react-native application.

Fixed by installing 12.1.0

**Comment by edritech93** [comment]
same issue for me
"react-native-webview": "^12.2.0",

**Comment by mganandraj** [comment]
Hello everyone .. This is caused by https://github.com/react-native-webview/react-native-webview/commit/75e7801a6255b37f6887d29d10b9ba688e051416 which I merged a couple of days ago to mitigate large number of crashes reported in some OEM devices. 

The motivation behind the fix was to leverage the change https://android-review.googlesource.com/c/platform/frameworks/support/+/1978527 which added a workaround to the androidx.core module to avoid stripping the File provider metadata.

The fix to androidx.core is available from https://developer.android.com/jetpack/androidx/releases/core#core-1.8.0-alpha06 (which was released more than an year ago) onwards. Could you folks upgrade to this version to avoid the crash ? Transitive dependency can be explicitly resolved as @mlazari suggested above https://github.com/react-native-webview/react-native-webview/issues/2978#issuecomment-1573469986

Thanks !

**Comment by Nensi9** [comment]
getting the same issue.
```

"react": "18.2.0",
"react-native": "0.71.8",
"react-native-webview": "^12.2.0"

```

**Comment by valery-lavrik** [comment]
I don't want to change **build.gradle** files because in the future, when you have to update **react-native**, there will be problems with editing these files. 
I think it would be more correct to roll back to version **12.1.0** for now and wait for a fix from the developer

**Comment by AbhavThakur** [comment]
> I don't want to change **build.gradle** files because in the future, when you have to update **react-native**, there will be problems with editing these files. I think it would be more correct to roll back to version **12.1.0** for now and wait for a fix from the developer

Actually in Build.gradle we are using the latest version by default react-native us using old version .So, when we update in future we will not get any error.

**Comment by TomCorvus** [comment]
Hi there,
Solution above is working but not really safe. Forcing AndroidX Core to 1.10.1 can cause errors on other dependencies during build. Downgrade to 12.1.0 version is the best solution until the problem is solved or instruction is given.

Use the tilde on your dependency version range to avoid getting next minor version like `"react-native-webview": "~12.1.0"`

**Comment by mganandraj** [comment]
I'm looking into making the usage of the new construction conditional on the availability of the new version of android modules .. Please hold on.

**Comment by billnbell** [comment]
> I'm looking into making the usage of the new construction conditional on the availability of the new version of android modules .. Please hold on.

OK. yeah unsure when react-native and all modules will support 1.8.0 and up.

**Comment by Titozzz** [comment]
@mganandraj I'll revert while we find a solution to fix most people issues, keeping this open for follow up

**Comment by mganandraj** [comment]
> @mganandraj I'll revert while we find a solution to fix most people issues, keeping this open for follow up

Hi @Titozzz Sure, please go ahead with the revert. 

I will continue investigating on getting this change back in a way that works with all versions of androidx libraries. We should also try to get react native to transitive depend on newer androidx versions.

For short term, I can add a local patch.

(By the way, Sorry for introducing this situation. I didn’t realize that so many codebases are still referring to the old version of androidx.core library.)

**Comment by arihirsch** [comment]
Upping this, 12.2.0 doesn't work for me either. Same error as OP
