### ISSUE TITLE
Execution failed for task ':react-native-webview:compileDebugKotlin' 

### ISSUE THREAD

**Issue by sdinesmvc** [react-native-webview/react-native-webview#2593]
**Bug description:**

After installing the lib and building the project it fails with the following error:
npm install --save react-native-webview

**To Reproduce:**
Just run the below commands
npx react-native start
npx react-native run-android
I got the error as react-native-webview:compileDebugKotlin FAILED

**Expected behavior:**
Just build the application on the Android phone.

**Screenshots/Videos:**

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-webview:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 41s

    at makeError (D:\Dinesh\POC\ReactNativeCli\MyReactNativeTSProject\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at D:\Dinesh\POC\ReactNativeCli\MyReactNativeTSProject\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (D:\Dinesh\POC\ReactNativeCli\MyReactNativeTSProject\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (D:\Dinesh\POC\ReactNativeCli\MyReactNativeTSProject\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details. 

**Environment:**
 - OS: Windows 10
 - OS version:
 - react-native version: 0.69.1
 - react-native-webview version:11.22.5

**Comment by kinkin626** [comment]
+1 same issue after upgrading RN to 0.69.1

**Comment by kinkin626** [comment]
Solved this by including  **classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.0"** in root build.gradle

**Comment by sdinesmvc** [comment]
thanks @kinkin626  it working as a charm
