### ISSUE TITLE
When I update my sdk to 33 out of 32 I get this problem

### ISSUE THREAD

**Issue by aboalidev** [react-native-webview/react-native-webview#3107]
When I update my sdk to 33 out of 32 I get this problem

/Users/macbookpro/Desktop/WAStatusSaver2022/app/src/main/java/com/aboalidev/statussaver/waweb/WAWebActivity.java:131: error: cannot find symbol
mWebView.getSettings().setAppCacheEnabled(false); // deprecated
^
symbol: method setAppCacheEnabled(boolean)
location: class WebSettings

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:
 - OS version:
 - react-native version:
 - react-native-webview version:

**Comment by aditya-keri-betterhalf** [comment]
@aboalidev 
You'll need to upgrade the library to `11.22.7` at least.
https://github.com/react-native-webview/react-native-webview/pull/2583

**Comment by alexandreerick** [comment]
> 

It worked. I was using version 11.13.0.

**Comment by aboalidev** [comment]
> 

how
