### ISSUE TITLE
v11.18.0 is broken

### ISSUE THREAD

**Issue by birdofpreyru** [react-native-webview/react-native-webview#2421]
I have an Android app working fine with v11.17.2 of **react-native-webview**; if upgraded to v11.18.0 it crashes when it tries to render Webview with the error
> requireNativeComponent: "RNCWebView" was not found in the UIManager.

**Comment by sdb-dev** [comment]
We are having the same issue, both iOS and Android are crashing with the same error

**Comment by kuboshiba** [comment]
I have the same issue, both iOS and Android.
But I happened in v11.13.0

An error has occurred in this environment.
>  "react": "16.9.0",
    "react-native": "^0.61.5",
    "react-native-webview": "^11.13.0",

I also noticed an error during the build.
`warn Package react-native-webview has been ignored because it contains invalid configuration. Reason: Cannot find module 'react-native-test-app/package.json'`

**Comment by Stackerr** [comment]
I have same issue, android 

> "react": "^17.0.2",
> "react-native": "^0.67.3",
> "react-native-webview": "^11.17.2",

**Comment by Sledziux** [comment]
I have same issue
` "react": "17.0.2",
  "react-native": "^0.67.1",
  "react-native-webview": "^11.18.0",
`

**Comment by takanorihirai** [comment]
same issue on `npx react-native run-ios` 
> "react": "^17.0.2",
> "react-native": "~0.63.4",
> "react-native-webview": "^11.17.2",

**Comment by mohita-lgg** [comment]
Any fix for this issue ? Downgrading the version is also not working.

**Comment by dhamodar** [comment]
Same issue so can i get any fixes

**Comment by ivari** [comment]
Same for us.

**Comment by spyshower** [comment]
We downgraded to `11.7.2` and it worked.

**Comment by yangfuzhang** [comment]
> We are having the same issue, both iOS and Android are crashing with the same error
> 
> I noticed the following error now pops up during build: `warn Package react-native-webview has been ignored because it contains invalid configuration. Reason: Cannot find module 'react-native-test-app/package.json'`

Got the same problem with v11.18.0 with this message during build, we downgraded to a lower version and it worked.

**Comment by mohita-lgg** [comment]
> > We are having the same issue, both iOS and Android are crashing with the same error
> > I noticed the following error now pops up during build: `warn Package react-native-webview has been ignored because it contains invalid configuration. Reason: Cannot find module 'react-native-test-app/package.json'`
> 
> Got the same problem with v11.18.0 with this message during build, we downgraded to a lower version and it worked.

Which lower version worked for you?

**Comment by yangfuzhang** [comment]
> > > We are having the same issue, both iOS and Android are crashing with the same error
> > > I noticed the following error now pops up during build: `warn Package react-native-webview has been ignored because it contains invalid configuration. Reason: Cannot find module 'react-native-test-app/package.json'`
> > 
> > 
> > Got the same problem with v11.18.0 with this message during build, we downgraded to a lower version and it worked.
> 
> Which lower version worked for you?

react-native-webview `11.15.0` works for me.
And my react-native version is:  "react-native": "0.66.3",

**Comment by Brma1048** [comment]
@mohita-lgg maybe try to clean all things up with this command: `rm -rf node_modules/ && rm -rf yarn.lock && rm -rf ios/Podfile.lock && pod repo update && yarn install` 
For me downgrading to react-native-webview: 11.17.2 worked

**Comment by lfalkner** [comment]
I've tried downgrading but the pod is not installing as expected. I don't receive an error from pod install. The same pod _did_ install for me earlier today, as well as for my teammate. Downgrading to `11.17.2` did not have any effect.

```
"react": "17.0.2,
"react-native": "0.65.2",
"react-native-webview": "^11.18.0",
```

**Comment by sdb-dev** [comment]
> I've tried downgrading but the pod is not installing as expected. I don't receive an error from pod install. The same pod _did_ install for me earlier today, as well as for my teammate. Downgrading to `11.17.2` did not have any effect.
> 
> ```
> "react": "17.0.2,
> "react-native": "0.65.2",
> "react-native-webview": "^11.18.0",
> ```

Set it to "11.17.2", without "^"

**Comment by Bilal-Abdeen** [comment]
I confirm that downgrading worked for me. Here are the steps, which I followed. 
On `<project_folder>\package.json`: 
change `"react-native-webview": "^11.18.0"` to `"react-native-webview": "11.17.2"`

On MS Windows: 
`rd node_modules /q /s`
`npm install`

**Comment by aprilmintacpineda** [comment]
Same here, we're waiting for fix too.

**Comment by VictorYuan666** [comment]
I solve this problem by 
`yarn add react-native-test-app -D`

**Comment by mohita-lgg** [comment]
> @mohita-lgg maybe try to clean all things up with this command: `rm -rf node_modules/ && rm -rf yarn.lock && rm -rf ios/Podfile.lock && pod repo update && yarn install` For me downgrading to react-native-webview: 11.17.2 worked

Clean and re-install worked for me. Thanks.

**Comment by erdugen** [comment]
> > I've tried downgrading but the pod is not installing as expected. I don't receive an error from pod install. The same pod _did_ install for me earlier today, as well as for my teammate. Downgrading to `11.17.2` did not have any effect.
> > ```
> > "react": "17.0.2,
> > "react-native": "0.65.2",
> > "react-native-webview": "^11.18.0",
> > ```
> 
> Set it to `"11.17.2"`, without `^`

It is worked. Thanks.
What is diffrent `^` ?

**Comment by billnbell** [comment]
can we get a fix!?!?! Real one besides downgrading?

**Comment by MidKnightXI** [comment]
> > > I've tried downgrading but the pod is not installing as expected. I don't receive an error from pod install. The same pod _did_ install for me earlier today, as well as for my teammate. Downgrading to `11.17.2` did not have any effect.
> > > ```
> > > "react": "17.0.2,
> > > "react-native": "0.65.2",
> > > "react-native-webview": "^11.18.0",
> > > ```
> > 
> > 
> > Set it to `"11.17.2"`, without `^`
> 
> It is worked. Thanks. What is diffrent `^` ?

I guess that the ^ allow npm or yarn to install a more recent version if available

**Comment by erdugen** [comment]
> > > > I've tried downgrading but the pod is not installing as expected. I don't receive an error from pod install. The same pod _did_ install for me earlier today, as well as for my teammate. Downgrading to `11.17.2` did not have any effect.
> > > > ```
> > > > "react": "17.0.2,
> > > > "react-native": "0.65.2",
> > > > "react-native-webview": "^11.18.0",
> > > > ```
> > > 
> > > 
> > > Set it to `"11.17.2"`, without `^`
> > 
> > 
> > It is worked. Thanks. What is diffrent `^` ?
> 
> I guess that the ^ allow npm or yarn to install a more recent version if available

I found it https://semver.npmjs.com/

**Comment by TomCorvus** [comment]
Hi there, rollback to `11.17.2` version fix the issue.
Don't forget to remove the caret before the version number (For those who don't read previous answers)

To explain it:
`~11.17.2` will update you to all future patch versions, without incrementing the minor version number. ~11.17.2 will use releases from 11.17.2 to <11.18.0.
`^11.17.2` will update you to all future minor/patch versions, without incrementing the major version number. ^11.17.2 will use releases from 11.17.2 to <12.0.0 (so will use 11.18.0 version)

https://docs.npmjs.com/cli/v6/using-npm/semver#tilde-ranges-123-12-1
https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004

**Comment by TheAlmightyBob** [comment]
Duplicate of #2430, which was fixed by #2413

(I realize that this issue was actually opened first, but it wasn't the one referenced in the PR that fixed it)
